export { TIPOS_EVENTO, TIPOS_COMANDO } from "./registro";
export type {
  EventoDominio,
  HandlerEvento,
  IBusEventos,
} from "./types";
export type {
  ContactoCreadoPayload,
  ContactoActualizadoPayload,
  ContactoEliminadoPayload,
  EmpresaCreadaPayload,
  EmpresaActualizadaPayload,
  OportunidadCreadaPayload,
  EtapaCambiadaPayload,
  OportunidadGanadaPayload,
  OportunidadPerdidaPayload,
  ActividadCreadaPayload,
  ActividadCompletadaPayload,
  ProductoCreadoPayload,
  ProductoActualizadoPayload,
  CotizacionCreadaPayload,
  CotizacionEnviadaPayload,
  PedidoCreadoPayload,
  PedidoActualizadoPayload,
  PedidoEntregadoPayload,
  ComandoEnviarMensajePayload,
  ComandoProcesarEntrantePayload,
  ComandoMarcarLeidoPayload,
  ComandoEnviarEmailPayload,
  ComandoInicializarInstanciaPayload,
} from "./registro";
